### ISSUE TITLE
unable to parse redirect field errors reply

### ISSUE THREAD

**Issue by cyberb** [syncloud/insider#8]
```
root@raspberrypi:~# insider --debug acquire_domain test@example.com pass1234 pi      
2015-01-15 23:22:04,010 - Reader - INFO - reading /proc/cpuinfo
2015-01-15 23:22:04,015 - Reader - DEBUG - contents: processor  : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
Features        : swp half thumb fastmult vfp edsp java tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2708
Revision        : 0010
Serial          : 00000000be6d9ba0

2015-01-15 23:22:04,024 - CpuInfo - DEBUG - processor = 0
2015-01-15 23:22:04,028 - CpuInfo - DEBUG - model name = ARMv6-compatible processor rev 7 (v6l)
2015-01-15 23:22:04,033 - CpuInfo - DEBUG - Features = swp half thumb fastmult vfp edsp java tls
2015-01-15 23:22:04,036 - CpuInfo - DEBUG - CPU implementer = 0x41
2015-01-15 23:22:04,041 - CpuInfo - DEBUG - CPU architecture = 7
2015-01-15 23:22:04,045 - CpuInfo - DEBUG - CPU variant = 0x0
2015-01-15 23:22:04,049 - CpuInfo - DEBUG - CPU part = 0xb76
2015-01-15 23:22:04,053 - CpuInfo - DEBUG - CPU revision = 7
2015-01-15 23:22:04,058 - CpuInfo - DEBUG - Hardware = BCM2708
2015-01-15 23:22:04,823 - dns - ERROR - {
  "message": "There's a error in parameters", 
  "parameters_messages": [
    {
      "messages": [
        "Too short (< 5)"
      ], 
      "parameter": "user_domain"
    }
  ]
}
2015-01-15 23:22:04,832 - app - ERROR - dictionary update sequence element #0 has length 1; 2 is required
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/syncloud/app/main.py", line 31, in run
    data = runner()
  File "/usr/local/lib/python2.7/dist-packages/syncloud/app/main.py", line 47, in <lambda>
    run(lambda: call(method, vars(args)), args.debug, text, exit_code_on_error)
  File "/usr/local/lib/python2.7/dist-packages/syncloud/app/main.py", line 17, in call
    return func(**params)
  File "/usr/local/lib/python2.7/dist-packages/syncloud/insider/facade.py", line 53, in acquire_domain
    result = self.dns.acquire(email, password, user_domain)
  File "/usr/local/lib/python2.7/dist-packages/syncloud/insider/dns.py", line 62, in acquire
    self.check_http_error(response)
  File "/usr/local/lib/python2.7/dist-packages/syncloud/insider/dns.py", line 47, in check_http_error
    error = convertible.from_json(response.text)
  File "/usr/local/lib/python2.7/dist-packages/convertible.py", line 82, in from_json
    return to_object(jsonpickle.decode(json_text), obj_type)
  File "/usr/local/lib/python2.7/dist-packages/convertible.py", line 57, in to_object
    return Struct(structure)
  File "/usr/local/lib/python2.7/dist-packages/convertible.py", line 28, in __init__
    self.__dict__[k] = to_object(v)
  File "/usr/local/lib/python2.7/dist-packages/convertible.py", line 56, in to_object
    return [to_object(item) for item in structure]
  File "/usr/local/lib/python2.7/dist-packages/convertible.py", line 57, in to_object
    return Struct(structure)
  File "/usr/local/lib/python2.7/dist-packages/convertible.py", line 28, in __init__
    self.__dict__[k] = to_object(v)
  File "/usr/local/lib/python2.7/dist-packages/convertible.py", line 56, in to_object
    return [to_object(item) for item in structure]
  File "/usr/local/lib/python2.7/dist-packages/convertible.py", line 57, in to_object
    return Struct(structure)
  File "/usr/local/lib/python2.7/dist-packages/convertible.py", line 25, in __init__
    self.__dict__.update(adict)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
{
  "message": "dictionary update sequence element #0 has length 1; 2 is required", 
  "data": {}, 
  "success": false
}
```

**Comment by vsapronov** [comment]
Can we close this? It seems to be fixed now...

**Comment by cyberb** [comment]
Sure
